### ISSUE TITLE
can not match on `Name`

### ISSUE THREAD

**Issue by KisaragiEffective** [picoHz/mediatype#1]
Hello, I'm using `0.19.4` on my project.
When I do insert \[code 1\], the compiler says:
> to use a constant of type `mediatype::Name` in a pattern, `mediatype::Name` must be annotated with `#[derive(PartialEq, Eq)]`

Would you like to apply the suggestion? Thank you.

\[code 1\]
```rs
        use mediatype::names;
        match (mediatype.ty, mediatype.subty) {
            (names::TEXT, names::MARKDOWN) => {
                Ok(SupportedContentType::Markdown)
            }
            (names::TEXT, names::PLAIN) => {
                Ok(SupportedContentType::PlainText)
            }
            (names::TEXT, names::HTML) => {
                Ok(SupportedContentType::Html)
            }
            (names::APPLICATION, names::OCTET_STREAM) => {
                Ok(SupportedContentType::GpgEncrypted)
            }
            _ => bail!("unsupported content type")
        }
```

**Comment by picoHz** [comment]
Unfortunately, it is impossible to use name constants in that way due to Rust's limitation. The `Name` struct implements custom `PartialEq` and `Eq` for the case-insensitive comparison but Rust does not allow such types in pattern matches.

This restriction is explained in [RFC 1445](https://github.com/rust-lang/rfcs/blob/master/text/1445-restrict-constants-in-patterns.md).
